name: Deploy React App to AWS Amplify

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Checks-out repository under $GITHUB_WORKSPACE, so job can access it

      - name: Read .nvmrc
        run: echo NVMRC=$(cat .nvmrc) >> $GITHUB_OUTPUT
        id: nvm

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Install Dependencies
        run: npm install # Install npm dependencies

      - name: Build
        run: npm run build # Build React application

  deploy:
    runs-on: ubuntu-latest
    needs: build # This job runs after the build job is successfully completed

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          # Replace with your AWS region

      - name: Deploy to AWS Amplify
        run: amplify publish
